### ISSUE TITLE
latest node and postgis version

### ISSUE THREAD

**Issue by adamtang79** [am2222/strapi-plugin-postgis#16]
Hi Author,

Anyway to bump up the version for

nodejs: v18.17.1 lts
postgis: v3.3.3

**Comment by am2222** [comment]
Hi @adamtang79  I have been so bust recently! I will try to have a look at this but it should not have any breaking changes if you upgrade them.

Did you get any errors when you tried to upgrade them?

**Comment by baznikin** [comment]
Yes, there are error message:
```
error strapi-plugin-postgis@0.1.8: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.19.0"
error Found incompatible module.
```

**Comment by baznikin** [comment]
Also recent strapi do not support node 16 - https://docs.strapi.io/dev-docs/installation/cli#preparing-the-installation

**Comment by g-nardiello** [comment]
Hi, is this plugin still maintained?
The current version is not compatible with the latest versions of strapi

**Comment by am2222** [comment]
@g-nardiello I will try to update this library to latest version in incoming weeks

**Comment by jael0x** [comment]
Hi there! I just found this plugin, any news about the update?

**Comment by am2222** [comment]
Hi @jael0x I am planning for upgrading it with strapi version 5 once it is released
